"""username field lengthe max to 20

Revision ID: c3493f3b6ffe
Revises: e033f7673113
Create Date: 2024-12-14 20:17:29.835946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
"""
importing sqlmodel
"""
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c3493f3b6ffe'
down_revision: Union[str, None] = 'e033f7673113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
